apiVersion: v1
kind: Service
metadata:
  name: ecom-app-service
  labels:
    app: ecom-app
spec:
  selector:
    app: ecom-app
  type: LoadBalancer  # Exposes the service via AWS LoadBalancer
  ports:
  - protocol: TCP
    port: 80         # External port to expose
    targetPort: 5000 # Flask app container port
